### ISSUE TITLE
configs.py

### ISSUE THREAD

**Issue by Geethi2020** [UW-Madison-Lee-Lab/LanguageInterfacedFineTuning#2]
Hi,
 Could you please help with the configurations to run LIFT classification ? Couldn't locate configs.py module. 
Thank you.

**Comment by lisha1992** [comment]
> Hi, Could you please help with the configurations to run LIFT classification ? Couldn't locate configs.py module. Thank you.

Hi, I have the same issue, could you please share the configs.py file? 
Thank you!

**Comment by UW-Madison-Lee-Lab** [comment]
We would like to sincerely thank you for bringing the issue to our attention. We have uploaded the configs.py file to the folder classification/utils/configs.py. Feel free to let us know if you have other questions!

**Comment by Geethi2020** [comment]
@UW-Madison-Lee-Lab  Thank you for uploading configs.py. 
I was trying to run `/classification/run_exps/run_gpt3.py ` but getting error like 
`AttributeError: module 'utils.configs' has no attribute 'in_context_num_prompts'`. Same with `sample_size` too. Are these attributes to be added to the configs module according to the dataset used ? Could you share some sample values used in your testing ? Thank you.

**Comment by yzeng58** [comment]
We have updated the new `configs.py` to https://github.com/UW-Madison-Lee-Lab/LanguageInterfacedFineTuning/blob/master/classification/utils/configs.py. Let us know if there are any other problems!
