### ISSUE TITLE
Inquiry of package version

### ISSUE THREAD

**Issue by wwweiwei** [UW-Madison-Lee-Lab/LanguageInterfacedFineTuning#3]
Hi,

Thank you so much for releasing the code.
I have encountered some problems with package version; therefore, I cannot reproduce the results.
Could you provide environment.yml or an instruction of package version, please? Thank you!

**Comment by yzeng58** [comment]
Hi @wwweiwei,

Thanks for reaching out! We are glad to hear that you are interested in our code. Our team has uploaded the environment configuration file at the following link: https://github.com/UW-Madison-Lee-Lab/LanguageInterfacedFineTuning/blob/master/environment_lift.yml. This file should help you resolve the package version issues you mentioned and successfully reproduce the results. If you have any further questions or concerns, please don't hesitate to reach out.
