### ISSUE TITLE
Your OpenAI key is exposed in one of of your Python scripts

### ISSUE THREAD

**Issue by ahuang11** [UW-Madison-Lee-Lab/LanguageInterfacedFineTuning#6]
Not sure if it's already revoked, but just wanted to let you know.

**Comment by yzeng58** [comment]
Dear ahuang11,

Thank you so much for bringing this to our attention. We have removed all OpenAI keys from our code and replaced them with placeholders instructing users to insert their own keys. Rest assured, all previous keys have been invalidated and are no longer in use.

Thanks again!

Best regards,
Yuchen Zeng on behalf of all authors
